version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: strapi_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapipassword}
      POSTGRES_DB: ${DATABASE_NAME:-strapi_db}
    ports:
      - "5432:5432"
    volumes:
      - strapi_data:/var/lib/postgresql/data

  strapi:
    container_name: strapi_app
    build: .
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME:-strapi_db}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapipassword}
      DATABASE_SSL: 'false'
      
      # Claves de la app
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      
      # Cloudinary Config
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER}
    ports:
      - "1337:1337"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    depends_on:
      - postgres

volumes:
  strapi_data: